name: Run Python App

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to main branch

jobs:
  run-python-app:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    strategy:
      matrix:
        worker: [1]  # Define 5 workers in the matrix

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository

    - name: Set up Python 3.9
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: 3.9  # Specify the Python version

    - name: Install dependencies
      run: |
        pip install requests ecdsa pycryptodome base58

    - name: Run the Python app
      run: |
        python app.py  # Run your Python script
