name: Keyhunt Build and Run

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Update
    - name: Update
      run: |
        sudo apt update
    
    # Step 2: Install Required Dependencies
    - name: Install Dependencies
      run: |
        sudo apt install git build-essential libssl-dev libgmp-dev -y

    # Step 3: Clone the Keyhunt Repository
    - name: Clone Keyhunt Repo
      run: |
        git clone https://github.com/albertobsd/keyhunt.git
        cd keyhunt
    
    # Step 4: Compile Keyhunt
    - name: Build Keyhunt
      run: |
        cd keyhunt
        make

    # Step 5: Create the Test File
    - name: Create Test File
      run: |
        echo "1BY8GQbnueYofwSuFAT3USAhGjPrkxDdW9" > keyhunt/tests/67.rmd

    # Step 6: Run Keyhunt with Specified Parameters
    - name: Run Keyhunt
      run: |
        cd keyhunt
        ./keyhunt -f tests/67.rmd  -m bsgs -t 4 -k 256 -s 0 -S -r 40000000000000000:41000000000000000
