name: Run Super Vanitygen with Multiple Workers

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-address:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [1, 2, 3, 4, 5]  # Defines 5 parallel workers
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Super Vanitygen Repository
        run: |
          git clone https://github.com/klynastor/supervanitygen.git
          cd supervanitygen

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make autoconf libtool libgmp3-dev

      - name: Build Super Vanitygen
        run: |
          cd supervanitygen
          make  # Assuming there's a Makefile in the repo

      - name: Run Super Vanitygen
        run: |
          cd supervanitygen
          ./vanitygen "1Turjaun${{ matrix.worker }}"  # Adjust prefix for each worker
