name: Download and Upload Videos

on:
  push:
    branches:
      - main

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        sudo apt install ffmpeg
        python -m pip install --upgrade pip
        pip install yt-dlp requests telethon tqdm

    - name: Download Video
      run: python download.py

    - name: List files after download
      run: ls

    - name: Upload Video
      run: python upload.py
      
